### PR TITLE
Update pvl_disc.py

### PR DESCRIPTION
**Pull request by Jorissup**
Heya,

Just trying out your code, and realized you had (Kt <= 0.6 - 1) for some reason, so changed them

### CODE REVIEW

**Comment by Calama-Consulting** [comment]
Thanks! Your change checks out against the original document (http://rredc.nrel.gov/solar/pubs/PDFs/TR-215-3087.pdf) eqn. 3-9 to 3-14

Good catch!

**Comment by Jorissup** [comment]
No problem :)

Was also wondering If I could use the python library for a web simulation
tool.
This tool will allow a user to see how the change of a PV's orientation
effects it's Power output.
It's part of a project i'm doing for the University of Waikato, New Zealand.

If so how would you like me to reference your organisation and library?

Many Thanks,
Joris Suppers

**Comment by Calama-Consulting** [comment]
Please reference the original work by Sandia National Labs and PVPMC, and this open source project. In the future we will have a better attribution system in place, but for now do your best to reference it back.

**Comment by Jorissup** [comment]
Webpage tool is up:

http://nzspot.cms.waikato.ac.nz/

Have a try!

On Sun, Feb 15, 2015 at 8:06 AM, Calama-Consulting <notifications@github.com

**Comment by wholmgren** [comment]
Neat tool. Please consider adding it to the [wiki](https://github.com/pvlib/pvlib-python/wiki/Projects-and-publications-that-use-pvlib-python) at the new organization. This Sandia-Labs repository is no longer maintained.

**Pull request merged**
